Very early stage of Erlang Driver
bblfsh/erlang-driver pull request #1
Opened 2017-03-29 07:50 UTC by dpaz

2017-03-29 07:54 UTC, dpaz commented
Example of current in/out

`{"content":"fun()-> io:write(\"foo\")end.\n fun()-> io:write(\"foo2\")end."}`
```
[{'fun',1,
       {clauses,[{clause,1,[],[],
                         [{call,1,
                                {remote,1,{atom,1,io},{atom,1,write}},
                                [{string,1,"foo"}]}]}]}},
{'fun',2,
       {clauses,[{clause,2,[],[],
                         [{call,2,
                                {remote,2,{atom,2,io},{atom,2,write}},
                                [{string,2,"foo2"}]}]}]}}]```

2017-03-29 08:27 UTC, smola commented on native/src/driver_app.erl
> +%%====================================================================
Unless this is some kind of convention in the Erlang community, do not use these kind of fat section separators.

2017-03-29 08:27 UTC, smola commented on native/src/driver_app.erl
> +read_input() ->
This function does not do what it says. It says "Read input as a string", but it seems it also tokenizes and parses.

2017-04-03 16:27 UTC, smola requested changes

2017-04-03 16:27 UTC, smola commented on Dockerfile.build.tpl
> +# Dockerfile.build represents the build environment of the driver, used during
Remove these comments. These are just for reference when creating the driver.

2017-04-03 16:27 UTC, smola commented on Dockerfile.build.tpl
> +# To avoid files written in the volume by root or foreign users, we create a
Remove this comment.

2017-04-03 16:27 UTC, smola commented on Dockerfile.build.tpl
> +# As minimal build tools you need: make, curl and git, install using the same
Remove this comment.

2017-04-03 16:27 UTC, smola commented on Dockerfile.build.tpl
> +# The volume with the full source code is mounted at `/opt/driver/src` so, we
Remove this comment.

2017-04-03 16:27 UTC, smola commented on Dockerfile.tpl
> +# Dockerfile represents the container being use to run the driver, should be
Same here.

2017-04-03 16:27 UTC, smola commented on driver/main.go
> +package main
You have to update bblfsh-sdk and run `bblfsh-sdk update` again, since we updated `main.go` again. Impact should be minimal.

2017-04-03 16:27 UTC, smola commented on manifest.toml
> +# native_version describes the version or versions being use to build and
remove these comments from the original template; leave only any specific comment you want to add, if any.

2017-04-03 16:27 UTC, smola commented on native/native.sh
> +/opt/driver/bin/$DIR/$RELEASE/bin/$RELEASE foreground
Use `exec` to run stuff on bash.

2017-04-03 16:27 UTC, smola commented on native/run.sh
> +_build/default/rel/pre-alpha/bin/pre-alpha foreground
`exec` here

2017-04-06 09:50 UTC, smola approved these changes

2017-04-06 09:50 UTC, merged